### PR TITLE
Added support for new package naming convention in Fedora 20 and RHEL/Ce...

### PR DESCRIPTION
**Pull request by rbowlby**
Also:
Added centos 7 to kitchen platforms being tested.
Added serverspec intregration tests that pass for all platforms.

### CODE REVIEW

**Comment by nathenharvey** [comment]
:+1:

**Comment by lamont-granquist** [comment]
:+1:

**Comment by charlesjohnson** [comment]
:+1:

**Comment by lamont-granquist** [comment]
hmmm, no travis for PRs on this repo so i just whack merge and pray?

**Comment by lamont-granquist** [comment]
no travis at all....

**Pull request merged**
